export const ON_PAGE_LOAD = 'ON_PAGE_LOAD'
export const GET_COURSE_START = 'GET_COURSE_START'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_ERROR = 'GET_COURSE ERROR'
export const GET_USER_START = "GET_COURSES_START"
export const GET_USER_ERROR = "GET_COURSES_ERROR"
export const GET_USER_SUCCESS = "GET_COURSES_SUCCESS"
